// <auto-generated />
using ElectronicsStore.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectronicsStore.Persistence.Migrations
{
    [DbContext(typeof(EStoreDbContext))]
    [Migration("20221220164549_data")]
    partial class data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectronicsStore.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 3,
                            Name = "NoName"
                        });
                });

            modelBuilder.Entity("ElectronicsStore.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Phones"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Devices"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accesories"
                        });
                });

            modelBuilder.Entity("ElectronicsStore.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdBrand")
                        .HasColumnType("int");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdBrand");

                    b.HasIndex("IdCategory");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdBrand = 1,
                            IdCategory = 1,
                            Name = "iPhone 13 Pro Max",
                            Price = 109.99m
                        },
                        new
                        {
                            Id = 2,
                            IdBrand = 3,
                            IdCategory = 1,
                            Name = "OnePlus 9",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 3,
                            IdBrand = 2,
                            IdCategory = 1,
                            Name = "Galaxy S21 FE",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 12,
                            IdBrand = 1,
                            IdCategory = 1,
                            Name = "iPhone 14 Pro Max",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 13,
                            IdBrand = 1,
                            IdCategory = 1,
                            Name = "iPhone 13",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 14,
                            IdBrand = 1,
                            IdCategory = 1,
                            Name = "iPhone 11",
                            Price = 69.99m
                        },
                        new
                        {
                            Id = 15,
                            IdBrand = 1,
                            IdCategory = 1,
                            Name = "iPhone 12",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 16,
                            IdBrand = 1,
                            IdCategory = 1,
                            Name = "iPhone 12 Max",
                            Price = 95.99m
                        },
                        new
                        {
                            Id = 4,
                            IdBrand = 1,
                            IdCategory = 2,
                            Name = "iPad Pro 12,9",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 5,
                            IdBrand = 3,
                            IdCategory = 3,
                            Name = "Silver Monkey Kabel",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 6,
                            IdBrand = 3,
                            IdCategory = 3,
                            Name = "Microsoft 1850 Mouse",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 7,
                            IdBrand = 3,
                            IdCategory = 3,
                            Name = "NuPhy Air75 Red, Gateron",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 8,
                            IdBrand = 3,
                            IdCategory = 2,
                            Name = "Xiaomi Pad 5",
                            Price = 69.99m
                        },
                        new
                        {
                            Id = 9,
                            IdBrand = 2,
                            IdCategory = 2,
                            Name = "Galaxy Tab A8",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 10,
                            IdBrand = 3,
                            IdCategory = 2,
                            Name = "Huawei MatePad Paper",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 11,
                            IdBrand = 3,
                            IdCategory = 3,
                            Name = "ASUS RT-AC51",
                            Price = 29.99m
                        });
                });

            modelBuilder.Entity("ElectronicsStore.Entities.Product", b =>
                {
                    b.HasOne("ElectronicsStore.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("IdBrand")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectronicsStore.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
